/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNoData: typeof import('./src/components/AppNoData.vue')['default']
    CartSummary: typeof import('./src/components/CartSummary.vue')['default']
    ChatMessage: typeof import('./src/components/support/ChatMessage.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    ConfirmationDialog: typeof import('./src/components/ConfirmationDialog.vue')['default']
    CountrySelector: typeof import('./src/components/CountrySelector.vue')['default']
    CurrencySelector: typeof import('./src/components/CurrencySelector.vue')['default']
    DigitalTicketCard: typeof import('./src/components/ticket/DigitalTicketCard.vue')['default']
    EventCard: typeof import('./src/components/EventCard.vue')['default']
    FormItems: typeof import('./src/components/FormItems.vue')['default']
    FormItemsEditable: typeof import('./src/components/FormItemsEditable.vue')['default']
    ImageManager: typeof import('./src/components/ImageManager.vue')['default']
    IntentForm: typeof import('./src/components/support/IntentForm.vue')['default']
    Lightbox: typeof import('./src/components/Lightbox.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    NoItemsFound: typeof import('./src/components/NoItemsFound.vue')['default']
    OTPVerification: typeof import('./src/components/support/OTPVerification.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    PaymentOrangeMoney: typeof import('./src/components/payment/PaymentOrangeMoney.vue')['default']
    PaymentStripe: typeof import('./src/components/payment/PaymentStripe.vue')['default']
    Phone: typeof import('./src/components/Phone.vue')['default']
    ProductCard: typeof import('./src/components/product/ProductCard.vue')['default']
    ProductForm: typeof import('./src/components/product/ProductForm.vue')['default']
    ProductList: typeof import('./src/components/product/ProductList.vue')['default']
    ProgressLoader: typeof import('./src/components/ProgressLoader.vue')['default']
    QuickIntentButtons: typeof import('./src/components/support/QuickIntentButtons.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SupportBot: typeof import('./src/components/support/SupportBot.vue')['default']
    TicketDialog: typeof import('./src/components/TicketDialog.vue')['default']
    TicketDisplayDialog: typeof import('./src/components/counter/TicketDisplayDialog.vue')['default']
    TimePicker: typeof import('./src/components/TimePicker.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
  }
}
