/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'homepage': RouteRecordInfo<'homepage', '/', Record<never, never>, Record<never, never>>,
    'event-landing-slug': RouteRecordInfo<'event-landing-slug', '/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    'attendee-form-slug': RouteRecordInfo<'attendee-form-slug', '/:slug/attendee-form', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    'checkout-slug': RouteRecordInfo<'checkout-slug', '/:slug/checkout', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    'shop-slug': RouteRecordInfo<'shop-slug', '/:slug/shop', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    'event-register-success-slug': RouteRecordInfo<'event-register-success-slug', '/:slug/success', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    'tickets-slug': RouteRecordInfo<'tickets-slug', '/:slug/tickets', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    'admin-dashboard': RouteRecordInfo<'admin-dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'export-data-admin': RouteRecordInfo<'export-data-admin', '/admin/export-data', Record<never, never>, Record<never, never>>,
    'admin-organizations': RouteRecordInfo<'admin-organizations', '/admin/organizations', Record<never, never>, Record<never, never>>,
    'admin-review': RouteRecordInfo<'admin-review', '/admin/review', Record<never, never>, Record<never, never>>,
    'settings-admin': RouteRecordInfo<'settings-admin', '/admin/settings', Record<never, never>, Record<never, never>>,
    'admin-ticket-counters': RouteRecordInfo<'admin-ticket-counters', '/admin/ticket-counters', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/attendee', Record<never, never>, Record<never, never>>,
    'recent-orders': RouteRecordInfo<'recent-orders', '/attendee/recent-orders', Record<never, never>, Record<never, never>>,
    '/auth/': RouteRecordInfo<'/auth/', '/auth', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/auth/register', Record<never, never>, Record<never, never>>,
    'reset-password': RouteRecordInfo<'reset-password', '/auth/reset-password', Record<never, never>, Record<never, never>>,
    'signin': RouteRecordInfo<'signin', '/auth/signin', Record<never, never>, Record<never, never>>,
    'signout': RouteRecordInfo<'signout', '/auth/signout', Record<never, never>, Record<never, never>>,
    '/counter/': RouteRecordInfo<'/counter/', '/counter', Record<never, never>, Record<never, never>>,
    'counter-pos': RouteRecordInfo<'counter-pos', '/counter/pos', Record<never, never>, Record<never, never>>,
    'counter-sessions': RouteRecordInfo<'counter-sessions', '/counter/sessions', Record<never, never>, Record<never, never>>,
    'counter-shift-end': RouteRecordInfo<'counter-shift-end', '/counter/shift-end', Record<never, never>, Record<never, never>>,
    'counter-shift-start': RouteRecordInfo<'counter-shift-start', '/counter/shift-start', Record<never, never>, Record<never, never>>,
    '/event/': RouteRecordInfo<'/event/', '/event', Record<never, never>, Record<never, never>>,
    '/event/[eventId]/': RouteRecordInfo<'/event/[eventId]/', '/event/:eventId', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    'event-attendees': RouteRecordInfo<'event-attendees', '/event/:eventId/attendees', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    'event-checkin': RouteRecordInfo<'event-checkin', '/event/:eventId/checkin', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    'event-config': RouteRecordInfo<'event-config', '/event/:eventId/config', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    'event-edit': RouteRecordInfo<'event-edit', '/event/:eventId/edit', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    'import': RouteRecordInfo<'import', '/event/:eventId/import', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    'event-landing-config': RouteRecordInfo<'event-landing-config', '/event/:eventId/landing-config', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    'event-manage-shop': RouteRecordInfo<'event-manage-shop', '/event/:eventId/manage-shop', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    'dashboard-organizer-event-product-orders': RouteRecordInfo<'dashboard-organizer-event-product-orders', '/event/:eventId/product-orders', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    'event-promo-codes': RouteRecordInfo<'event-promo-codes', '/event/:eventId/promo-codes', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    '/event/[eventId]/qr/': RouteRecordInfo<'/event/[eventId]/qr/', '/event/:eventId/qr', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    'qr-viewer': RouteRecordInfo<'qr-viewer', '/event/:eventId/qr/:registrationId/:attendeeId/:qrUuid', { eventId: ParamValue<true>, registrationId: ParamValue<true>, attendeeId: ParamValue<true>, qrUuid: ParamValue<true> }, { eventId: ParamValue<false>, registrationId: ParamValue<false>, attendeeId: ParamValue<false>, qrUuid: ParamValue<false> }>,
    'event-staff': RouteRecordInfo<'event-staff', '/event/:eventId/staff', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    'event-statistics': RouteRecordInfo<'event-statistics', '/event/:eventId/statistics', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    'event-tickets': RouteRecordInfo<'event-tickets', '/event/:eventId/tickets', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    'event-visitors': RouteRecordInfo<'event-visitors', '/event/:eventId/visitors', { eventId: ParamValue<true> }, { eventId: ParamValue<false> }>,
    'event-add': RouteRecordInfo<'event-add', '/event/add', Record<never, never>, Record<never, never>>,
    'events-browse': RouteRecordInfo<'events-browse', '/events', Record<never, never>, Record<never, never>>,
    'form-builder': RouteRecordInfo<'form-builder', '/form-builder', Record<never, never>, Record<never, never>>,
    'manage-index': RouteRecordInfo<'manage-index', '/manage', Record<never, never>, Record<never, never>>,
    'manage-sales-logs': RouteRecordInfo<'manage-sales-logs', '/manage/sales-logs', Record<never, never>, Record<never, never>>,
    'not-found': RouteRecordInfo<'not-found', '/NotFound', Record<never, never>, Record<never, never>>,
    '/organization/': RouteRecordInfo<'/organization/', '/organization', Record<never, never>, Record<never, never>>,
    'organization-add': RouteRecordInfo<'organization-add', '/organization/add', Record<never, never>, Record<never, never>>,
    'credential-generate': RouteRecordInfo<'credential-generate', '/organization/credential/:organizationId', { organizationId: ParamValue<true> }, { organizationId: ParamValue<false> }>,
    'organization-edit': RouteRecordInfo<'organization-edit', '/organization/edit/:organizationId?', { organizationId?: ParamValueZeroOrOne<true> }, { organizationId?: ParamValueZeroOrOne<false> }>,
    '/organizer/': RouteRecordInfo<'/organizer/', '/organizer', Record<never, never>, Record<never, never>>,
    'dashboard-organizer': RouteRecordInfo<'dashboard-organizer', '/organizer/dashboard', Record<never, never>, Record<never, never>>,
    'organizer-staff': RouteRecordInfo<'organizer-staff', '/organizer/staff', Record<never, never>, Record<never, never>>,
    'organizer-verify': RouteRecordInfo<'organizer-verify', '/organizer/verify', Record<never, never>, Record<never, never>>,
    'payment-cancel': RouteRecordInfo<'payment-cancel', '/payment/cancel', Record<never, never>, Record<never, never>>,
    'payment-return': RouteRecordInfo<'payment-return', '/payment/return', Record<never, never>, Record<never, never>>,
    'pricing': RouteRecordInfo<'pricing', '/Pricing', Record<never, never>, Record<never, never>>,
    'privacy': RouteRecordInfo<'privacy', '/privacy', Record<never, never>, Record<never, never>>,
    '/staff/': RouteRecordInfo<'/staff/', '/staff', Record<never, never>, Record<never, never>>,
    'staff-dashboard': RouteRecordInfo<'staff-dashboard', '/staff/dashboard', Record<never, never>, Record<never, never>>,
    'staff-checkin': RouteRecordInfo<'staff-checkin', '/staff/scanner', Record<never, never>, Record<never, never>>,
    'support': RouteRecordInfo<'support', '/support', Record<never, never>, Record<never, never>>,
    'terms': RouteRecordInfo<'terms', '/terms', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: 'homepage'
      views: never
    }
    'src/pages/[slug]/index.vue': {
      routes: 'event-landing-slug'
      views: never
    }
    'src/pages/[slug]/attendee-form.vue': {
      routes: 'attendee-form-slug'
      views: never
    }
    'src/pages/[slug]/checkout.vue': {
      routes: 'checkout-slug'
      views: never
    }
    'src/pages/[slug]/shop.vue': {
      routes: 'shop-slug'
      views: never
    }
    'src/pages/[slug]/success.vue': {
      routes: 'event-register-success-slug'
      views: never
    }
    'src/pages/[slug]/tickets.vue': {
      routes: 'tickets-slug'
      views: never
    }
    'src/pages/admin/index.vue': {
      routes: '/admin/'
      views: never
    }
    'src/pages/admin/dashboard.vue': {
      routes: 'admin-dashboard'
      views: never
    }
    'src/pages/admin/export-data.vue': {
      routes: 'export-data-admin'
      views: never
    }
    'src/pages/admin/organizations.vue': {
      routes: 'admin-organizations'
      views: never
    }
    'src/pages/admin/review.vue': {
      routes: 'admin-review'
      views: never
    }
    'src/pages/admin/settings.vue': {
      routes: 'settings-admin'
      views: never
    }
    'src/pages/admin/ticket-counters.vue': {
      routes: 'admin-ticket-counters'
      views: never
    }
    'src/pages/attendee/index.vue': {
      routes: 'profile'
      views: never
    }
    'src/pages/attendee/recent-orders.vue': {
      routes: 'recent-orders'
      views: never
    }
    'src/pages/auth/index.vue': {
      routes: '/auth/'
      views: never
    }
    'src/pages/auth/register.vue': {
      routes: 'register'
      views: never
    }
    'src/pages/auth/reset-password.vue': {
      routes: 'reset-password'
      views: never
    }
    'src/pages/auth/signin.vue': {
      routes: 'signin'
      views: never
    }
    'src/pages/auth/signout.vue': {
      routes: 'signout'
      views: never
    }
    'src/pages/counter/index.vue': {
      routes: '/counter/'
      views: never
    }
    'src/pages/counter/pos.vue': {
      routes: 'counter-pos'
      views: never
    }
    'src/pages/counter/sessions.vue': {
      routes: 'counter-sessions'
      views: never
    }
    'src/pages/counter/shift-end.vue': {
      routes: 'counter-shift-end'
      views: never
    }
    'src/pages/counter/shift-start.vue': {
      routes: 'counter-shift-start'
      views: never
    }
    'src/pages/event/index.vue': {
      routes: '/event/'
      views: never
    }
    'src/pages/event/[eventId]/index.vue': {
      routes: '/event/[eventId]/'
      views: never
    }
    'src/pages/event/[eventId]/attendees/index.vue': {
      routes: 'event-attendees'
      views: never
    }
    'src/pages/event/[eventId]/checkin/index.vue': {
      routes: 'event-checkin'
      views: never
    }
    'src/pages/event/[eventId]/config/index.vue': {
      routes: 'event-config'
      views: never
    }
    'src/pages/event/[eventId]/edit/index.vue': {
      routes: 'event-edit'
      views: never
    }
    'src/pages/event/[eventId]/import/index.vue': {
      routes: 'import'
      views: never
    }
    'src/pages/event/[eventId]/landing-config/index.vue': {
      routes: 'event-landing-config'
      views: never
    }
    'src/pages/event/[eventId]/manage-shop/index.vue': {
      routes: 'event-manage-shop'
      views: never
    }
    'src/pages/event/[eventId]/product-orders/index.vue': {
      routes: 'dashboard-organizer-event-product-orders'
      views: never
    }
    'src/pages/event/[eventId]/promo-codes/index.vue': {
      routes: 'event-promo-codes'
      views: never
    }
    'src/pages/event/[eventId]/qr/index.vue': {
      routes: '/event/[eventId]/qr/'
      views: never
    }
    'src/pages/event/[eventId]/qr/[registrationId]/[attendeeId]/[qrUuid].vue': {
      routes: 'qr-viewer'
      views: never
    }
    'src/pages/event/[eventId]/staff/index.vue': {
      routes: 'event-staff'
      views: never
    }
    'src/pages/event/[eventId]/statistics/index.vue': {
      routes: 'event-statistics'
      views: never
    }
    'src/pages/event/[eventId]/tickets/index.vue': {
      routes: 'event-tickets'
      views: never
    }
    'src/pages/event/[eventId]/visitors/index.vue': {
      routes: 'event-visitors'
      views: never
    }
    'src/pages/event/add/index.vue': {
      routes: 'event-add'
      views: never
    }
    'src/pages/events/index.vue': {
      routes: 'events-browse'
      views: never
    }
    'src/pages/form-builder.vue': {
      routes: 'form-builder'
      views: never
    }
    'src/pages/manage/index.vue': {
      routes: 'manage-index'
      views: never
    }
    'src/pages/manage/sales-logs.vue': {
      routes: 'manage-sales-logs'
      views: never
    }
    'src/pages/NotFound.vue': {
      routes: 'not-found'
      views: never
    }
    'src/pages/organization/index.vue': {
      routes: '/organization/'
      views: never
    }
    'src/pages/organization/add/index.vue': {
      routes: 'organization-add'
      views: never
    }
    'src/pages/organization/credential/[organizationId].vue': {
      routes: 'credential-generate'
      views: never
    }
    'src/pages/organization/edit/[[organizationId]].vue': {
      routes: 'organization-edit'
      views: never
    }
    'src/pages/organizer/index.vue': {
      routes: '/organizer/'
      views: never
    }
    'src/pages/organizer/dashboard.vue': {
      routes: 'dashboard-organizer'
      views: never
    }
    'src/pages/organizer/staff/index.vue': {
      routes: 'organizer-staff'
      views: never
    }
    'src/pages/organizer/verify/index.vue': {
      routes: 'organizer-verify'
      views: never
    }
    'src/pages/payment/cancel.vue': {
      routes: 'payment-cancel'
      views: never
    }
    'src/pages/payment/return.vue': {
      routes: 'payment-return'
      views: never
    }
    'src/pages/Pricing.vue': {
      routes: 'pricing'
      views: never
    }
    'src/pages/privacy.vue': {
      routes: 'privacy'
      views: never
    }
    'src/pages/staff/index.vue': {
      routes: '/staff/'
      views: never
    }
    'src/pages/staff/dashboard.vue': {
      routes: 'staff-dashboard'
      views: never
    }
    'src/pages/staff/scanner.vue': {
      routes: 'staff-checkin'
      views: never
    }
    'src/pages/support/index.vue': {
      routes: 'support'
      views: never
    }
    'src/pages/terms.vue': {
      routes: 'terms'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
